"""agregar_contenido_talleres_y_progreso

Revision ID: 3b467c30ae39
Revises: af422e34fecb
Create Date: 2025-06-30 11:42:05.814237

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b467c30ae39'
down_revision = 'af422e34fecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contenido_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo_contenido', sa.String(length=50), nullable=False),
    sa.Column('dia_programa', sa.Integer(), nullable=True),
    sa.Column('url_contenido', sa.String(length=500), nullable=True),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('es_obligatorio', sa.Boolean(), nullable=True),
    sa.Column('fecha_disponible', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['taller_id'], ['talleres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_contenido',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contenido_id', sa.Integer(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=True),
    sa.Column('fecha_completado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contenido_id'], ['contenido_taller.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'contenido_id')
    )
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.drop_table('progreso_contenido')
    op.drop_table('contenido_taller')
    # ### end Alembic commands ###
