"""agregar_nivel_actividad_a_talleres

Revision ID: 569a17291f70
Revises: 3b467c30ae39
Create Date: 2025-06-30 13:11:34.777010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '569a17291f70'
down_revision = '3b467c30ae39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel_actividad', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_column('nivel_actividad')

    # ### end Alembic commands ###
