"""cambiar_horario_por_dias_semana_en_talleres

Revision ID: 6112efb44bdf
Revises: 569a17291f70
Create Date: 2025-06-30 13:22:22.109862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6112efb44bdf'
down_revision = '569a17291f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        # Primero agregar la columna como nullable
        batch_op.add_column(sa.Column('dias_semana', sa.String(length=100), nullable=True))
    
    # Convertir los datos existentes de horario a dias_semana
    connection = op.get_bind()
    
    # Mapeo de horarios típicos a días de la semana
    horario_a_dias = {
        '9:00 - 10:00': 'Lunes y Miércoles',
        '18:00 - 19:00': 'Martes y Jueves', 
        '16:00 - 17:00': 'Miércoles y Viernes',
        '10:00 - 11:30': 'Lunes, Miércoles y Viernes',
        '19:00 - 20:30': 'Martes y Jueves',
        '17:00 - 18:00': 'Lunes y Miércoles',
        '8:00 - 9:00': 'Todos los días',
        '18:30 - 19:30': 'Lunes a Viernes',
        '12:00 - 13:00': 'Martes y Jueves'
    }
    
    # Actualizar cada registro
    result = connection.execute(sa.text("SELECT id, horario FROM talleres"))
    for row in result:
        dias = horario_a_dias.get(row.horario, 'Lunes, Miércoles y Viernes')  # Default
        connection.execute(
            sa.text("UPDATE talleres SET dias_semana = :dias WHERE id = :id"),
            {"dias": dias, "id": row.id}
        )
    
    # Ahora hacer la columna NOT NULL y eliminar horario
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('dias_semana', nullable=False)
        batch_op.drop_column('horario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        # Agregar columna horario de vuelta
        batch_op.add_column(sa.Column('horario', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    
    # Restaurar datos de horario desde dias_semana (mapeo inverso simplificado)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE talleres SET horario = '10:00 - 11:00' WHERE dias_semana IS NOT NULL"))
    
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.alter_column('horario', nullable=False)
        batch_op.drop_column('dias_semana')

    # ### end Alembic commands ###
