"""agregar_campo_fecha_a_talleres

Revision ID: af422e34fecb
Revises: a7c37194e212
Create Date: 2025-06-30 00:22:54.954972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af422e34fecb'
down_revision = 'a7c37194e212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
