"""empty message

Revision ID: d54b58fce4d0
Revises: 678d628b48bb
Create Date: 2025-06-26 23:00:14.334305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd54b58fce4d0'
down_revision = '678d628b48bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
