"""empty message

Revision ID: dee1bad3b19b
Revises: d54b58fce4d0
Create Date: 2025-06-26 23:02:31.521762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee1bad3b19b'
down_revision = 'd54b58fce4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objetivo', sa.String(length=50), nullable=False))
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talleres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('objetivo')

    # ### end Alembic commands ###
