"""Agregar campos peso, altura y actividad al usuario

Revision ID: fc9cf8e5d651
Revises: 67a71b110dce
Create Date: 2025-06-27 23:47:25.762827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9cf8e5d651'
down_revision = '67a71b110dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('altura', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('actividad', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('actividad')
        batch_op.drop_column('altura')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
